using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Recolorable;

[GenerateTypedNameReferences]
public sealed partial class LayerColorEditor : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private EntityUid _target;
    private readonly List<int> _layerIndices = new();

    public LayerColorEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LayerList.OnItemSelected += OnLayerSelected;
        ColorSliders.OnColorChanged += OnColorChanged;
    }

    public void SetTarget(EntityUid uid)
    {
        _target = uid;
        Preview.SetEntity(uid);

        LayerList.Clear();
        _layerIndices.Clear();

        if (!_entMan.TryGetComponent<SpriteComponent>(uid, out var sprite))
            return;

        for (var i = 0; i < sprite.AllLayers.Count(); i++)
        {
            var label = sprite.TryGetLayer(i, out var layer)
                ? layer.ToString()
                : $"Layer {i}";

            LayerList.AddItem(label!);
            _layerIndices.Add(i);
        }
    }

    private void OnLayerSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (!_entMan.TryGetComponent<SpriteComponent>(_target, out var sprite))
            return;

        var index = _layerIndices[args.ItemIndex];
        ColorSliders.Color = sprite[index].Color;
    }

    private void OnColorChanged(Color color)
    {
        var selected = LayerList.GetSelected().FirstOrDefault();
        if (selected == null)
            return;

        var listIndex = LayerList.IndexOf(selected);
        var layerIndex = _layerIndices[listIndex];

        if (_entMan.TryGetComponent<SpriteComponent>(_target, out var sprite))
            sprite.LayerSetColor(layerIndex, color);
    }
}

