using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Clothing.Components;
using Content.Shared.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.SS220.Recolorable;

[GenerateTypedNameReferences]
public sealed partial class LayerColorEditor : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private SpriteSystem _spriteSystem = default!;

    private EntityUid _target;
    private EntityUid? _previewTarget;
    private EntityUid? _clothingDummy;

    private Dictionary<int, Color> _layerColors = new();
    private Dictionary<int, bool> _layerVisible = new();
    private readonly List<int> _layerIndices = new();

    public LayerColorEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        LayerList.OnItemSelected += OnLayerSelected;
        LayerList.OnItemDeselected += OnLayerDeselect;
        ColorSliders.OnColorChanged += OnColorChanged;
    }

    private void OnLayerDeselect(ItemList.ItemListDeselectedEventArgs args)
    {
        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        var index = _layerIndices[args.ItemIndex];
        if (!_spriteSystem.TryGetLayer((preview, sprite), index, out var layer, false))
            return;

        var wasVisible = _layerVisible[index];
        _spriteSystem.LayerSetVisible((preview, sprite), index, wasVisible);
    }

    public void SetTarget(EntityUid uid)
    {
        _target = uid;

        if (_previewTarget is { } preview)
            _entManager.DeleteEntity(preview);

        if (_clothingDummy is { } dummy)
            _entManager.DeleteEntity(dummy);

        var metadata = _entManager.GetComponent<MetaDataComponent>(uid);
        if (metadata.EntityPrototype == null)
            return;

        _previewTarget = _entManager.SpawnEntity(metadata.EntityPrototype.ID, MapCoordinates.Nullspace);
        _clothingDummy =_entManager.SpawnEntity("MobHumanDummy", MapCoordinates.Nullspace);

        if (_entManager.TryGetComponent<ClothingComponent>(_target, out var clothingComponent)
            && TryGetFirstMatchingSlot(_clothingDummy.Value, clothingComponent.Slots, out var slot))
        {
            ClothingVisualsPreview.Visible = true;
            _clothingDummy =_entManager.SpawnEntity("MobHumanDummy", MapCoordinates.Nullspace);
            ClothingVisualsPreview.SetEntity(_clothingDummy);

            _entManager.System<InventorySystem>()
                .TryEquip(_clothingDummy.Value,
                    _previewTarget.Value,
                    slot,
                    true,
                    true
                    );

            var clothingLayers = clothingComponent.ClothingVisuals[slot];

            for (int i = 0; i < clothingLayers.Count; i++)
            {
                var label = $"Clothing Layer {i}";
                var currentLayer = clothingLayers[i];
                var wasVisible = currentLayer.Visible.GetValueOrDefault(false);
                var color = currentLayer.Color.GetValueOrDefault(Color.White);

                LayerList.AddItem(label);
                _layerIndices.Add(i);
                _layerVisible.Add(i, wasVisible);
                _layerColors.Add(i, color);
            }
        }
        else
        {
            ClothingVisualsPreview.Visible = false;
            _entManager.DeleteEntity(_clothingDummy);
        }

        Preview.SetEntity(_previewTarget);

        LayerList.Clear();
        _layerIndices.Clear();

        if (!_entManager.TryGetComponent<SpriteComponent>(uid, out var sprite))
            return;

        for (var i = _layerIndices.Count; i < sprite.AllLayers.Count(); i++)
        {
            // Maybe try to get the layer name?
            // var label = sprite.TryGetLayer(i, out var layer)
            //     ? layer.ToString()
            //     : $"Layer {i}";

            var label = $"Layer {i}";
            if (!_spriteSystem.TryGetLayer((uid, sprite), i, out var layer, false))
                return;

            var isVisible = layer.Visible;
            var color = layer.Color;

            LayerList.AddItem(label);
            _layerIndices.Add(i);
            _layerColors.Add(i, color);
            _layerVisible.Add(i, isVisible);
        }
    }

    private void OnLayerSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        var index = _layerIndices[args.ItemIndex];
        if (!_spriteSystem.TryGetLayer((preview, sprite), index, out var layer, false))
            return;

        ColorSliders.Color = layer.Color;
        _spriteSystem.LayerSetVisible((preview, sprite), index, true);
    }

    private void OnColorChanged(Color color)
    {
        var selected = LayerList.GetSelected().FirstOrDefault();
        if (selected == null)
            return;

        var listIndex = LayerList.IndexOf(selected);
        var layerIndex = _layerIndices[listIndex];

        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        _spriteSystem.LayerSetColor((preview, sprite), layerIndex, color);
    }

    public override void Close()
    {
        base.Close();
        if (_previewTarget is { } preview)
            _entManager.DeleteEntity(preview);
    }

    private bool TryGetFirstMatchingSlot(EntityUid dummy, SlotFlags flags, out string slotName)
    {
        slotName = string.Empty;

        if (!_entManager.System<InventorySystem>().TryGetSlots(dummy, out var slotDefs))
            return false;

        foreach (var slot in slotDefs)
        {
            if ((slot.SlotFlags & flags) != 0)
            {
                slotName = slot.Name;
                return true;
            }
        }

        return false;
    }
}

