using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Clothing.Components;
using Content.Shared.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.SS220.Recolorable;

[GenerateTypedNameReferences]
public sealed partial class LayerColorEditor : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private SpriteSystem _spriteSystem = default!;

    private EntityUid _target;
    private EntityUid? _previewTarget;
    private EntityUid? _previewEquipped;
    private EntityUid? _clothingDummy;

    private Dictionary<int, Color> _layerColors = new();
    private Dictionary<int, bool> _layerVisible = new();
    private readonly List<int> _layerIndices = new();

    private bool _isTargetClothing;
    private List<PrototypeLayerData> _clothingLayers = new();
    private readonly Dictionary<int, string> _clothingLayerKeys = new();

    public LayerColorEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        LayerList.OnItemSelected += OnLayerSelected;
        LayerList.OnItemDeselected += OnLayerDeselect;
        ColorSliders.OnColorChanged += OnColorChanged;
    }

    private void OnLayerDeselect(ItemList.ItemListDeselectedEventArgs args)
    {
        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        var index = _layerIndices[args.ItemIndex];
        if (!_spriteSystem.TryGetLayer((preview, sprite), index, out var layer, false))
            return;

        var wasVisible = _layerVisible[index];
        _spriteSystem.LayerSetVisible((preview, sprite), index, wasVisible);
    }

    public void SetTarget(EntityUid uid)
    {
        _target = uid;

        if (_previewTarget is { } preview)
            _entManager.DeleteEntity(preview);

        if (_clothingDummy is { } dummy)
            _entManager.DeleteEntity(dummy);

        LayerList.Clear();
        _layerIndices.Clear();
        _layerColors.Clear();
        _layerVisible.Clear();
        ClothingVisualsPreview.Visible = false;
        _isTargetClothing = false;
        _clothingLayerKeys.Clear();

        if (_entManager.HasComponent<ClothingComponent>(_target))
            _isTargetClothing = true;

        var metadata = _entManager.GetComponent<MetaDataComponent>(_target);
        _previewTarget = _entManager.SpawnEntity(metadata.EntityPrototype?.ID, MapCoordinates.Nullspace);
        Preview.SetEntity(_previewTarget);

        if (_isTargetClothing)
        {
            handleClothingColoring();
        }
        else
        {
            handleAnyOtherColoring();
        }
    }

    private void handleAnyOtherColoring()
    {
        if (!_entManager.TryGetComponent<SpriteComponent>(_target, out var sprite))
            return;

        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var previewSprite))
            return;

        for (var i = _layerIndices.Count; i < sprite.AllLayers.Count(); i++)
        {
            var label = $"Layer {i}";
            if (!_spriteSystem.TryGetLayer((_target, sprite), i, out var layer, false))
                return;

            var isVisible = layer.Visible;
            var color = layer.Color;

            LayerList.AddItem(label);
            _layerIndices.Add(i);
            _layerColors.Add(i, color);
            _layerVisible.Add(i, isVisible);

            _spriteSystem.LayerSetColor((preview, previewSprite), i, layer.Color);
            _spriteSystem.LayerSetVisible((preview, previewSprite), i, layer.Visible);
        }
    }

    private void handleClothingColoring()
    {
        _clothingDummy =_entManager.SpawnEntity("MobHuman", MapCoordinates.Nullspace);
        ClothingVisualsPreview.Visible = true;
        ClothingVisualsPreview.SetEntity(_clothingDummy);

        if (!_entManager.TryGetComponent<ClothingComponent>(_previewTarget, out var clothingComp))
            return;

        if (_clothingDummy is not {} dummy
            || !_entManager.TryGetComponent<SpriteComponent>(dummy, out var dummySpriteComp))
            return;

        if (_previewTarget == null)
            return;

        if (!TryGetFirstMatchingSlot(_clothingDummy.Value, clothingComp.Slots, out var equippableSlot))
            return;

        var metadata = _entManager.GetComponent<MetaDataComponent>(_target);
        _previewEquipped = _entManager.SpawnEntity(metadata.EntityPrototype?.ID, MapCoordinates.Nullspace);

        if (!_entManager.System<InventorySystem>()
            .TryEquip(_clothingDummy.Value,
                _previewEquipped.Value,
                equippableSlot,
                true,
                true
            ))
            return;

        var visuals = clothingComp.ClothingVisuals;
        if (!visuals.TryGetValue(equippableSlot, out var slotLayers))
            return;

        _clothingLayers = slotLayers;

        for (var i = 0; i < _clothingLayers.Count; i++)
        {
            var layerKey = slotLayers[i].MapKeys?.FirstOrDefault() ?? $"{equippableSlot}-{i}";

            if (!_spriteSystem.TryGetLayer((dummy, dummySpriteComp), layerKey, out var currentLayer, false))
                continue;

            LayerList.AddItem($"Layer {i}");
            _layerIndices.Add(i);
            _clothingLayerKeys[i] = layerKey;
            _layerVisible.Add(i, currentLayer.Visible);
            _layerColors.Add(i, currentLayer.Color);
        }
    }

    private void OnLayerSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        var index = _layerIndices[args.ItemIndex];
        if (!_spriteSystem.TryGetLayer((preview, sprite), index, out var layer, false))
            return;

        ColorSliders.Color = layer.Color;
        ColorSliders.Visible = true;
        _spriteSystem.LayerSetVisible((preview, sprite), index, true);


        if (_isTargetClothing)
        {
            _clothingLayers[index].Visible = true;
        }
    }

    private void OnColorChanged(Color color)
    {
        var selected = LayerList.GetSelected().FirstOrDefault();
        if (selected == null)
            return;

        var listIndex = LayerList.IndexOf(selected);
        var layerIndex = _layerIndices[listIndex];

        if (_previewTarget is not { } preview ||
            !_entManager.TryGetComponent<SpriteComponent>(preview, out var sprite))
            return;

        _spriteSystem.LayerSetColor((preview, sprite), layerIndex, color);

        if (!_isTargetClothing)
            return;

        _clothingLayers[layerIndex].Color = color;

        if (_clothingDummy is not { } dummy
            || !_entManager.TryGetComponent<SpriteComponent>(dummy, out var dummySprite)
            || !_clothingLayerKeys.TryGetValue(layerIndex, out var layerKey))
            return;

        _spriteSystem.LayerSetColor((dummy, dummySprite), layerKey, color);
    }

    public override void Close()
    {
        base.Close();
        if (_previewTarget is { } preview)
            _entManager.DeleteEntity(preview);
    }

    private bool TryGetFirstMatchingSlot(EntityUid dummy, SlotFlags flags, out string slotName)
    {
        slotName = string.Empty;

        if (!_entManager.System<InventorySystem>().TryGetSlots(dummy, out var slotDefs))
            return false;

        foreach (var slot in slotDefs)
        {
            if ((slot.SlotFlags & flags) != 0)
            {
                slotName = slot.Name;
                return true;
            }
        }

        return false;
    }
}

